# Generated by Django 5.1.6 on 2025-04-01 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_moderation', '0003_post_deepfake_score_post_deepfake_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deepfake', models.BooleanField(default=False, help_text='Final classification result')),
                ('deepfake_score', models.FloatField(blank=True, help_text='Confidence score for deepfake class', null=True)),
                ('real_score', models.FloatField(blank=True, help_text='Confidence score for real class', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('raw_result', models.JSONField(blank=True, help_text='Raw analysis result JSON', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text="Reason for failure if status is 'failed'", null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When analysis was completed', null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deepfake_analysis', to='content_moderation.post')),
            ],
            options={
                'verbose_name': 'Image Analysis',
                'verbose_name_plural': 'Image Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='deepfake_de_status_624482_idx'), models.Index(fields=['is_deepfake'], name='deepfake_de_is_deep_310fad_idx')],
            },
        ),
    ]
