# Generated by Django 4.2.19 on 2025-03-06 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('968b6a71-b29e-4d4f-8be2-4b88579f5dc9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
