# Generated by Django 4.2.19 on 2025-03-06 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0002_alter_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74234c38-aed0-46eb-9b12-7b06987b3a82'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
