# Generated by Django 5.1.6 on 2025-03-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='user',
        ),
    ]
