# Generated by Django 5.1.6 on 2025-04-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0002_post_disclaimer_alter_post_visibility_share_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deepfake_score',
            field=models.FloatField(blank=True, help_text='Confidence score for deepfake detection', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deepfake_status',
            field=models.CharField(choices=[('not_analyzed', 'Not Analyzed'), ('analyzing', 'Analyzing'), ('flagged', 'Flagged as Deepfake'), ('not_flagged', 'Not Flagged (Real)'), ('analysis_failed', 'Analysis Failed')], default='not_analyzed', help_text='Status of deepfake detection', max_length=20),
        ),
    ]
