# Generated by Django 5.2 on 2025-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
