# Generated by Django 5.1.6 on 2025-04-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0007_post_caption_post_tags'),
        ('content_moderation', '0008_report'),
    ]

    operations = [
    ]
