# Generated by Django 5.2 on 2025-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0008_tag'),
        ('content_moderation', '0009_merge_0007_post_caption_post_tags_0008_report'),
    ]

    operations = [
    ]
