# Generated by Django 5.2 on 2025-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0010_merge_20250420_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='published', max_length=10),
        ),
    ]
