# Generated by Django 5.1.7 on 2025-04-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0010_merge_20250420_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
