# Generated by Django 5.1.6 on 2025-04-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0011_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saved Post', 'verbose_name_plural': 'Saved Posts'},
        ),
        migrations.RenameField(
            model_name='savedpost',
            old_name='saved_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='savedpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
