# Generated by Django 5.1.6 on 2025-04-25 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderation', '0012_alter_savedpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.CharField(blank=True, help_text="Action taken by the moderator/admin (e.g., 'Post removed')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_author_username',
            field=models.CharField(blank=True, help_text='Username of the post author (back up)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='content_moderation.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='content_mod_user_id_a66ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', 'status'], name='content_mod_visibil_b29505_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', 'reporter'], name='content_mod_post_id_fc65d0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='content_mod_status_868d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='content_mod_created_426b30_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='content_mod_reporte_6ab189_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='content_mod_status_a4800d_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'reporter'), name='unique_report_per_post_per_user'),
        ),
    ]
