# Generated by Django 5.1.6 on 2025-04-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('report', 'Report')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('report', 'Report')], max_length=20),
        ),
    ]
