# Generated by Django 4.2.19 on 2025-03-06 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', help_text="User's profile picture.", null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Short description about the user (maximum 200 characters).', max_length=200)),
                ('location', models.CharField(blank=True, help_text="User's location (optional).", max_length=100)),
                ('website', models.URLField(blank=True, help_text='Personal or professional website link.', null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth (optional).", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the profile was last updated.')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
