# Generated by Django 4.2.19 on 2025-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/defaults.png', help_text="User's profile picture.", null=True, upload_to='avatars/'),
        ),
    ]
